import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MyWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MyWorld extends World
{

    /**
     * Constructor for objects of class MyWorld.
     * 
     */
    public MyWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(550, 872, 1); 
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {

        WallWidthBig wallWidthBig = new WallWidthBig();
        addObject(wallWidthBig,372,416);
        wallWidthBig.setLocation(296,392);
        WallWidthsmall wallWidthsmall = new WallWidthsmall();
        addObject(wallWidthsmall,248,157);
        WallWidthsmall wallWidthsmall2 = new WallWidthsmall();
        addObject(wallWidthsmall2,348,157);
        WallWidthsmall wallWidthsmall3 = new WallWidthsmall();
        addObject(wallWidthsmall3,453,157);
        WallWidthsmall wallWidthsmall4 = new WallWidthsmall();
        addObject(wallWidthsmall4,401,312);
        WallWidthsmall wallWidthsmall5 = new WallWidthsmall();
        addObject(wallWidthsmall5,450,312);
        WallWidthsmall wallWidthsmall6 = new WallWidthsmall();
        addObject(wallWidthsmall6,480,284);
        WallWidthsmall wallWidthsmall7 = new WallWidthsmall();
        addObject(wallWidthsmall7,431,284);
        WallWidthsmall wallWidthsmall8 = new WallWidthsmall();
        addObject(wallWidthsmall8,273,262);
        WallWidthsmall wallWidthsmall9 = new WallWidthsmall();
        addObject(wallWidthsmall9,169,286);
        WallWidthsmall wallWidthsmall10 = new WallWidthsmall();
        addObject(wallWidthsmall10,217,286);
        WallWidthsmall wallWidthsmall11 = new WallWidthsmall();
        addObject(wallWidthsmall11,243,286);
        wallWidthsmall11.setLocation(247,284);
        WallWidthsmall wallWidthsmall12 = new WallWidthsmall();
        addObject(wallWidthsmall12,376,338);
        WallWidthsmall wallWidthsmall13 = new WallWidthsmall();
        addObject(wallWidthsmall13,424,338);
        WallWidthsmall wallWidthsmall14 = new WallWidthsmall();
        addObject(wallWidthsmall14,452,338);
        WallWidthsmall wallWidthsmall15 = new WallWidthsmall();
        addObject(wallWidthsmall15,452,494);
        WallWidthsmall wallWidthsmall16 = new WallWidthsmall();
        addObject(wallWidthsmall16,247,442);
        WallWidthsmall wallWidthsmall17 = new WallWidthsmall();
        addObject(wallWidthsmall17,296,442);
        WallWidthsmall wallWidthsmall18 = new WallWidthsmall();
        addObject(wallWidthsmall18,196,260);
        WallWidthsmall wallWidthsmall19 = new WallWidthsmall();
        addObject(wallWidthsmall19,400,207);
        WallWidthsmall wallWidthsmall20 = new WallWidthsmall();
        addObject(wallWidthsmall20,449,207);
        WallWidthsmall wallWidthsmall21 = new WallWidthsmall();
        addObject(wallWidthsmall21,375,233);
        WallWidthsmall wallWidthsmall22 = new WallWidthsmall();
        addObject(wallWidthsmall22,424,232);
        wallWidthsmall22.setLocation(425,233);
        WallWidthMedium wallWidthMedium = new WallWidthMedium();
        addObject(wallWidthMedium,251,398);
        wallWidthMedium.setLocation(436,471);
        WallWidthMedium wallWidthMedium2 = new WallWidthMedium();
        addObject(wallWidthMedium2,436,184);
        wallWidthMedium2.setLocation(258,334);
        WallWidthsmall wallWidthsmall23 = new WallWidthsmall();
        addObject(wallWidthsmall23,200,334);
        wallWidthsmall23.setLocation(200,333);
        WallWidthMedium wallWidthMedium3 = new WallWidthMedium();
        addObject(wallWidthMedium3,300,364);
        wallWidthMedium3.setLocation(292,365);
        WallWidthsmall wallWidthsmall24 = new WallWidthsmall();
        addObject(wallWidthsmall24,228,362);
        wallWidthsmall24.setLocation(233,364);
        WallWidthMedium wallWidthMedium4 = new WallWidthMedium();
        addObject(wallWidthMedium4,442,256);
        wallWidthMedium4.setLocation(439,256);
        WallWidthExtrasmall wallWidthExtrasmall = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall,440,408);
        wallWidthExtrasmall.setLocation(366,363);
        WallWidthExtrasmall wallWidthExtrasmall2 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall2,426,159);
        wallWidthExtrasmall2.setLocation(416,157);
        WallWidthExtrasmall wallWidthExtrasmall3 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall3,212,199);
        wallWidthExtrasmall3.setLocation(239,130);
        WallWidthExtrasmall wallWidthExtrasmall4 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall4,145,181);
        wallWidthExtrasmall4.setLocation(158,183);
        WallWidthExtrasmall wallWidthExtrasmall5 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall5,235,223);
        wallWidthExtrasmall5.setLocation(183,207);
        WallWidthExtrasmall wallWidthExtrasmall6 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall6,365,313);
        wallWidthExtrasmall6.setLocation(654,423);
        wallWidthExtrasmall6.setLocation(460,416);
        WallWidthBig wallWidthBig2 = new WallWidthBig();
        addObject(wallWidthBig2,494,391);
        wallWidthBig2.setLocation(379,415);
        WallWidthMedium wallWidthMedium5 = new WallWidthMedium();
        addObject(wallWidthMedium5,280,408);
        wallWidthMedium5.setLocation(692,406);
        removeObject(wallWidthMedium5);
        WallWidthsmall wallWidthsmall25 = new WallWidthsmall();
        addObject(wallWidthsmall25,276,416);
        wallWidthsmall25.setLocation(278,415);
        WallWidthExtrasmall wallWidthExtrasmall7 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall7,543,256);
        wallWidthExtrasmall7.setLocation(385,254);
        WallWidthBig wallWidthBig3 = new WallWidthBig();
        addObject(wallWidthBig3,244,531);
        wallWidthBig3.setLocation(280,488);
        WallWidthBig wallWidthBig4 = new WallWidthBig();
        addObject(wallWidthBig4,281,540);
        wallWidthBig4.setLocation(240,513);
        WallWidthMedium wallWidthMedium6 = new WallWidthMedium();
        addObject(wallWidthMedium6,348,519);
        wallWidthMedium6.setLocation(679,436);
        removeObject(wallWidthMedium6);
        WallWidthsmall wallWidthsmall26 = new WallWidthsmall();
        addObject(wallWidthsmall26,344,542);
        wallWidthsmall26.setLocation(348,514);
        WallWidthBig wallWidthBig5 = new WallWidthBig();
        addObject(wallWidthBig5,531,364);
        wallWidthBig5.setLocation(228,568);
        WallWidthBig wallWidthBig6 = new WallWidthBig();
        addObject(wallWidthBig6,368,539);
        wallWidthBig6.setLocation(363,559);
        removeObject(wallWidthBig6);
        WallWidthMedium wallWidthMedium7 = new WallWidthMedium();
        addObject(wallWidthMedium6,344,562);
        wallWidthMedium6.setLocation(331,566);
        WallWidthsmall wallWidthsmall27 = new WallWidthsmall();
        addObject(wallWidthsmall27,418,555);
        wallWidthsmall27.setLocation(397,568);
        WallWidthBig wallWidthBig7 = new WallWidthBig();
        addObject(wallWidthBig6,282,531);
        wallWidthBig6.setLocation(248,543);
        WallWidthMedium wallWidthMedium8 = new WallWidthMedium();
        addObject(wallWidthMedium7,412,528);
        wallWidthMedium7.setLocation(390,534);
        wallWidthMedium7.setLocation(366,542);
        WallWidthMedium wallWidthMedium9 = new WallWidthMedium();
        addObject(wallWidthMedium8,512,398);
        wallWidthMedium8.setLocation(418,440);
        WallWidthsmall wallWidthsmall28 = new WallWidthsmall();
        addObject(wallWidthsmall28,542,420);
        wallWidthsmall28.setLocation(479,440);
        wallWidthExtrasmall6.setLocation(469,415);
        WallWidthMedium wallWidthMedium10 = new WallWidthMedium();
        addObject(wallWidthMedium9,265,460);
        wallWidthMedium9.setLocation(262,464);
        WallWidthsmall wallWidthsmall29 = new WallWidthsmall();
        addObject(wallWidthsmall29,341,462);
        wallWidthsmall29.setLocation(313,463);
        WallWidthMedium wallWidthMedium11 = new WallWidthMedium();
        addObject(wallWidthMedium10,188,312);
        wallWidthMedium10.setLocation(256,310);
        WallWidthsmall wallWidthsmall30 = new WallWidthsmall();
        addObject(wallWidthsmall30,201,310);
        wallWidthsmall30.setLocation(201,309);
        WallWidthMedium wallWidthMedium12 = new WallWidthMedium();
        addObject(wallWidthMedium11,224,234);
        wallWidthMedium11.setLocation(460,374);
        removeObject(wallWidthMedium11);
        WallWidthBig wallWidthBig8 = new WallWidthBig();
        addObject(wallWidthBig7,234,104);
        wallWidthBig7.setLocation(301,101);
        WallWidthBig wallWidthBig9 = new WallWidthBig();
        addObject(wallWidthBig8,376,121);
        wallWidthBig8.setLocation(420,100);
        WallWidthMedium wallWidthMedium13 = new WallWidthMedium();
        addObject(wallWidthMedium11,456,193);
        wallWidthMedium11.setLocation(447,182);
        WallWidthExtrasmall wallWidthExtrasmall8 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall8,524,228);
        wallWidthExtrasmall8.setLocation(492,181);
        WallWidthMedium wallWidthMedium14 = new WallWidthMedium();
        addObject(wallWidthMedium12,230,188);
        wallWidthMedium12.setLocation(231,183);
        WallWidthMedium wallWidthMedium15 = new WallWidthMedium();
        addObject(wallWidthMedium13,303,199);
        wallWidthMedium13.setLocation(303,181);
        WallWidthMedium wallWidthMedium16 = new WallWidthMedium();
        addObject(wallWidthMedium14,288,225);
        wallWidthMedium14.setLocation(229,232);
        WallWidthsmall wallWidthsmall31 = new WallWidthsmall();
        addObject(wallWidthsmall31,276,244);
        removeObject(wallWidthsmall31);
        WallWidthExtrasmall wallWidthExtrasmall9 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall9,276,252);
        wallWidthExtrasmall9.setLocation(284,233);
        WallWidthMedium wallWidthMedium17 = new WallWidthMedium();
        addObject(wallWidthMedium15,270,201);
        wallWidthMedium15.setLocation(258,204);
        WallWidthExtrasmall wallWidthExtrasmall10 = new WallWidthExtrasmall();
        addObject(wallWidthExtrasmall10,326,235);
        wallWidthExtrasmall10.setLocation(306,204);
        WallWidthBig wallWidthBig10 = new WallWidthBig();
        addObject(wallWidthBig9,389,142);
        wallWidthBig9.setLocation(376,129);
        WallsHeightSmall wallsHeightSmall = new WallsHeightSmall();
        addObject(wallsHeightSmall,150,428);
        wallsHeightSmall.setLocation(146,552);
        WallHeightMedium wallHeightMedium = new WallHeightMedium();
        addObject(wallHeightMedium,80,359);
        wallHeightMedium.setLocation(143,237);
        WallHeightMedium wallHeightMedium2 = new WallHeightMedium();
        addObject(wallHeightMedium2,88,386);
        wallHeightMedium2.setLocation(142,374);
        WallsHeightSmall wallsHeightSmall2 = new WallsHeightSmall();
        addObject(wallsHeightSmall2,86,471);
        wallsHeightSmall2.setLocation(144,473);
        wallsHeightSmall.setLocation(143,516);
        WallHeightMedium wallHeightMedium3 = new WallHeightMedium();
        addObject(wallHeightMedium3,544,236);
        wallHeightMedium3.setLocation(512,187);
        WallHeightMedium wallHeightMedium4 = new WallHeightMedium();
        addObject(wallHeightMedium4,548,272);
        wallHeightMedium4.setLocation(513,316);
        wallHeightMedium4.setLocation(511,329);
        WallsHeightSmall wallsHeightSmall3 = new WallsHeightSmall();
        addObject(wallsHeightSmall3,545,424);
        wallsHeightSmall3.setLocation(512,418);
        WallsHeightSmall wallsHeightSmall4 = new WallsHeightSmall();
        addObject(wallsHeightSmall4,520,488);
        wallsHeightSmall4.setLocation(509,469);
        WallsHeightSmall wallsHeightSmall5 = new WallsHeightSmall();
        addObject(wallsHeightSmall5,423,392);
        wallsHeightSmall5.setLocation(686,476);
        removeObject(wallsHeightSmall5);
        wallWidthsmall14.setLocation(464,338);
        WallHeightSmallLong wallHeightSmallLong = new WallHeightSmallLong();
        addObject(wallHeightSmallLong,464,338);
        wallHeightSmallLong.setLocation(296,300);
        WallHeightSmallLong wallHeightSmallLong2 = new WallHeightSmallLong();
        addObject(wallHeightSmallLong2,191,442);
        wallHeightSmallLong2.setLocation(322,259);
        WallHeightSmallLong wallHeightSmallLong3 = new WallHeightSmallLong();
        addObject(wallHeightSmallLong3,415,326);
        wallHeightSmallLong3.setLocation(350,245);
        WallHeightSmallLong wallHeightSmallLong4 = new WallHeightSmallLong();
        addObject(wallHeightSmallLong4,188,429);
        wallHeightSmallLong4.setLocation(195,423);
        WallHeightSmallLong wallHeightSmallLong5 = new WallHeightSmallLong();
        addObject(wallHeightSmallLong5,176,406);
        wallHeightSmallLong5.setLocation(175,393);
        WallHeightSmallLong wallHeightSmallLong6 = new WallHeightSmallLong();
        addObject(wallHeightSmallLong6,196,480);
        wallHeightSmallLong6.setLocation(175,476);
        wallWidthBig4.setLocation(173,496);
        wallsHeightSmall.setLocation(144,539);
        wallWidthBig5.setLocation(199,567);
        wallWidthMedium6.setLocation(316,569);
        wallHeightMedium3.setLocation(512,203);
        wallHeightMedium4.setLocation(512,263);
        wallsHeightSmall4.setLocation(509,461);
        wallsHeightSmall3.setLocation(515,436);
        wallsHeightSmall4.setLocation(512,457);
        wallWidthsmall29.setLocation(324,463);
        wallsHeightSmall2.setLocation(139,490);
        wallsHeightSmall.setLocation(140,536);
        wallHeightMedium2.setLocation(141,440);
        wallHeightMedium.setLocation(140,294);
        wallHeightMedium.setLocation(143,298);
        wallsHeightSmall3.setLocation(515,364);
        wallsHeightSmall4.setLocation(516,409);
        wallWidthBig4.setLocation(185,512);
        wallHeightMedium.setLocation(141,290);
        wallHeightMedium2.setLocation(147,333);
        wallsHeightSmall2.setLocation(140,483);
        wallsHeightSmall.setLocation(139,524);
        wallWidthBig4.setLocation(201,514);
        removeObject(wallWidthBig4);
        wallHeightMedium.setLocation(136,378);
        wallHeightMedium.setLocation(145,262);
        wallHeightMedium2.setLocation(139,318);
        wallsHeightSmall2.setLocation(138,468);
        wallHeightMedium2.setLocation(66,413);
        wallHeightMedium.setLocation(140,304);
        wallHeightMedium2.setLocation(140,372);
        wallsHeightSmall2.setLocation(138,480);
        wallHeightMedium2.setLocation(117,372);
        wallHeightMedium.setLocation(141,289);
        wallHeightMedium2.setLocation(139,378);
        wallsHeightSmall.setLocation(137,536);
        wallsHeightSmall2.setLocation(140,490);
        wallsHeightSmall.setLocation(137,515);
        WellHeightSmallBgt wellHeightSmallBgt = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt,456,525);
        wellHeightSmallBgt.setLocation(428,536);
        WellHeightSmallBgt wellHeightSmallBgt2 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt2,526,496);
        wellHeightSmallBgt2.setLocation(479,342);
        WellHeightSmallBgt wellHeightSmallBgt3 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt3,352,447);
        wellHeightSmallBgt3.setLocation(354,440);
        WellHeightSmallBgt wellHeightSmallBgt4 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt4,400,484);
        wellHeightSmallBgt4.setLocation(403,509);
        WellHeightSmallBgt wellHeightSmallBgt5 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt5,388,489);
        wellHeightSmallBgt5.setLocation(380,484);
        WellHeightSmallBgt wellHeightSmallBgt6 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt6,77,244);
        wellHeightSmallBgt6.setLocation(168,248);
        WellHeightSmallBgt wellHeightSmallBgt7 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt7,396,296);
        wellHeightSmallBgt7.setLocation(397,296);
        wellHeightSmallBgt7.setLocation(274,131);
        WellHeightSmallBgt wellHeightSmallBgt8 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt8,556,524);
        wellHeightSmallBgt8.setLocation(224,433);
        WellHeightSmallBgt wellHeightSmallBgt9 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt9,584,522);
        wellHeightSmallBgt9.setLocation(404,407);
        WellHeightSmallBgt wellHeightSmallBgt10 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt10,567,476);
        wellHeightSmallBgt10.setLocation(454,404);
        WellHeightSmallBgt wellHeightSmallBgt11 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt11,543,495);
        wellHeightSmallBgt11.setLocation(431,361);
        WellHeightSmallBgt wellHeightSmallBgt12 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt12,333,354);
        wellHeightSmallBgt12.setLocation(324,336);
        WellHeightSmallBgt wellHeightSmallBgt13 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt13,317,145);
        wellHeightSmallBgt13.setLocation(302,159);
        WellHeightSmallBgt wellHeightSmallBgt14 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt14,404,288);
        wellHeightSmallBgt14.setLocation(376,288);
        WellHeightSmallBgt wellHeightSmallBgt15 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt15,476,241);
        wellHeightSmallBgt15.setLocation(477,235);
        WellHeightSmallBgt wellHeightSmallBgt16 = new WellHeightSmallBgt();
        addObject(wellHeightSmallBgt16,388,203);
        wallWidthsmall19.setLocation(376,187);
        WallWidthMedium wallWidthMedium18 = new WallWidthMedium();
        addObject(wallWidthMedium16,280,529);
        wallWidthMedium16.setLocation(213,518);
        WallWidthMedium wallWidthMedium19 = new WallWidthMedium();
        addObject(wallWidthMedium17,302,502);
        wallWidthMedium17.setLocation(288,519);
        Astronot astronot = new Astronot();
        addObject(astronot,180,147);
        removeObject(wellHeightSmallBgt16);
        removeObject(wallWidthsmall19);
        removeObject(wallWidthsmall14);
        removeObject(wellHeightSmallBgt10);
        removeObject(wellHeightSmallBgt9);
        removeObject(wallHeightSmallLong);
        Crab crab = new Crab();
        addObject(crab,149,322);
        crab.setLocation(428,168);
        astronot.setLocation(240,145);
        Crab crab2 = new Crab();
        addObject(crab2,240,145);
        Crab crab3 = new Crab();
        addObject(crab3,362,403);
        astronot.setLocation(157,199);
        Crab crab4 = new Crab();
        addObject(crab4,157,199);
        astronot.setLocation(160,198);
        Crab crab5 = new Crab();
        addObject(crab5,381,244);
        Crab crab6 = new Crab();
        addObject(crab6,226,556);
        astronot.setLocation(181,165);
        removeObject(astronot);
        Astronot astronot1 = new Astronot();
        addObject(astronot,185,144);
    }
}